// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Defines and exports the Prisma configuration for the project.
 *
 * @remarks
 * This configuration specifies the schema file location, the migrations directory,
 * and the datasource connection URL (fetched from the environment variable `DATABASE_URL`).
 *
 * @example
 * ```typescript
 * export default defineConfig({
 *   schema: "prisma/schema.prisma",
 *   migrations: {
 *     path: "prisma/migrations",
 *   },
 *   datasource: {
 *     url: process.env["DATABASE_URL"]
 *   },
 * });
 * ```
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-schema
 */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]
  },
});
